---
title: "Hamilton Students Seminar Series - Meetings"
date: 2019-2020
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Meetings

## 1st meeting: June 4, 2019

## Summary

- The seminars will start at the end of September (start of term 2)
- A priori, we will have one seminar every week
- Abstracts should be asked to the speakers one week in advance, for us to advertise it and maybe make a small booklet after
- The schedule needs to be discussed over Slack:
  - The order can be voluntary
  - If no one volunteers to present at some date, we'll randomly assign a name
- Damien will check if there's any funding possibility for the seminars (for food, for example)
- In general, the pesenter's supervisor will not be invited, unless the presenter decides otherwise, for her or his own reasons 


## Action points

- Organise the mailing list - Hazel [TO DO]
- Set up (or check how to setup up) the webpage - Tristan [TO DO]
- Make a poll to decide the best day and time for the seminars - Bruna [DONE]
- After the day/time is decided, book the seminar room with Kate - Bruna  [TO DO]


## 2nd meeting: June 27, 2019

## Summary

  - We set up the day and time of the week for the seminars to be every Thursday at 11am; 
  - Hazel communicated that we'll have to use the current mailing
  list for advertising, and that the emails should be sent out by Kate/Rosemary; 
  - The seminars will start in September 26; 
  - The current schedule is available at:
  
  `https://docs.google.com/spreadsheets/d/1BkxZIgsHCDD-ASGVtmsn6NoN7O5q8lcvXDopfqrsvBk/edit?usp=sharing`
  - Apparently we can't get any money for food, but we'll try asking Ken 
  once more 

## Action points

- Book the seminar room with Kate - Bruna 
- Organise the mailing list - Hazel
- Set up (or check how to setup up) the webpage - Tristan

## 3rd meeting: 29th August

## Summary

  - We agreed to move the date of the first seminar to October 1, due to
  Bruna being away on September 24 
  - We agreed that the duration of the seminar will be flexible, 
  given that some presenters might want/have more details about their
  research than words to present. The presentations will  
  be between 30~50 minutes long, with 10 minutes of questions at maximum. 
  - The last presenter should be responsible for buying the next week's
  snacks, and this money will possible be refunded later. No rule
  needs to be applied to snacks, anything is welcomed. 
  - Damien will send out the first email to kick-off the seminars, 
  and after it Hazel & Bruna will be in charge of the 
  mailing list (added with whoever else signs in)
  
  
## Action points
  - **Damien**: will check at the Hamilton Staff meeting what is out
  budget for the coffee-break (the initial idea is 30 euros for the 
  first meeting, and 15 for the following ones)
  - **Hazel & Bruna**: need to finish setting up the mailing list and
  promoting
  - **Aoife**: will be resposible for making the weekly poster
  - **Matt**: will be responsible for buying the first coffee-break/snacks
  